### ISSUE TITLE
mappedIds missing in keggprofile_enrichment function 

### ISSUE THREAD

**Issue by AxenArk** [lakhanp1/omics_utils#1]
Hi Lakhan,

I found a small bug in the keggprofile_enrichment function from the s01_topGO_functions.R.
When keytype == keggIdColumn, codes between line 186 and 193 will be skipped and mappedIds will not be defined. This will cause an error "object 'mappedIds' not found". I just commented the if lines and it seems still work fine.

Best wishes,
Hang

**Comment by lakhanp1** [comment]
Thank you Hang for finding the issue. I have fixed it. Please use the new version of script.

Regards,
Lakhan.
